### PR TITLE
Support for sending addressComponents, and receiving identified result sets

### PR DESCRIPTION
**Pull request by ensemblebd**
You can send a JSON object optionally with an ID, and optionally with address components instead of a string. Original version only supported sending an array of strings for the query. Now supports both.

So we therefore need to be able to receive the JSON object response containing a query object (address components) and the result set matched to an ID that we sent in.

Also added the FormattedStreet property, since that is sent back as well.
And added support for the Error field which comes back when the result set is empty.

Extended (duplicate handler, & split apart to see the stages) example usage with new system:

```
                foreach(Address target in targets.Values.ToList()) {
                    String fullAddress=target.printFull();
                    target.geoRequest=new GeocodioAddressRequest() {
                        address = fullAddress,
                        city = target.City,
                        state = target.State,
                        zip = target.Zip,
                        street = target.Line1
                    };
                    if (!dispatchAddressList.ContainsValue(fullAddress)) {
                        dispatchAddressList.Add(target.ID, fullAddress);
                        dispatchAddresses.Add(target.ID,target);
                    } else {
                        int origin= dispatchAddressList.FirstOrDefault(x=>x.Value==fullAddress).Key;
                        if (!duplicateAddresses.ContainsKey(origin)) duplicateAddresses.Add(origin,new List<Address>() { 
                            target
                        });
                        else duplicateAddresses[origin].Add(target);
                    }
                }
                Dictionary<int,GeocodioAddressRequest> dispatch=new Dictionary<int,GeocodioAddressRequest>(); 
                foreach (Address addy in dispatchAddresses.Values) dispatch.Add(addy.ID,addy.geoRequest);

                Geocodio.Geocodio geo = new Geocodio.Geocodio(SystemVars.getSystemVar("GeoCoding API").Value);
                GeocodioBatchResponse bresponse=geo.GetGeolocations(dispatch);

                foreach(GeocodioBatchResult bresult in bresponse.Results) {
                    int ident= bresult.ID.ToInt32();
                    Address target = targets[ident];

                    GeocodioResult result=bresult.Response.Results.First();
                    if (String.IsNullOrEmpty(result.Error)) {
                        // do stuff with it.. it's valid
                    }
                }
```

### CODE REVIEW

**Comment by neptunecentury** [comment]
I reviewed your changes and am accepting the pull request.

**Comment by neptunecentury** [comment]
@ensemblebd I created a dev branch and made a few changes. There were some issues with sending some of the address components, namely the "zip" parameter which is actually supposed to be "postal_code". Also, the "number" parameter isn't an accepted parameter according to the docs. It's parsed from the street component, e.g. "1600 Amphitheatre Parkway".

When you have time, please check out the changes and see if they work for you. On a side note, I also moved the Error property to the GeocodioResponse object so a blank result object doesn't have to be added.

**Comment by ensemblebd** [comment]
Perfect! I ran into that issue too on the postal_code, it errors out when the city isn't specified. 
That looks great, I think that will work much better. Really appreciate the assistance and second pair of eyes on this!
They have such a great service, and for .Net, this project seems to be the clear solution.

**Comment by neptunecentury** [comment]
Ok, cool, I will probably write a few more tests for the console app then merge it to master. At which point, I may contact Geocodio to include this in their list of API libraries.

Thanks for your work on this, and please, if you feel you want to add more features, go ahead and add to dev.

**Pull request merged**
